### ISSUE TITLE
Publishing guidelines

### ISSUE THREAD

**Issue by Eiyeron** [Wifsimster/datagamer-api-v2#3]
(This is a copy of the previous issue, it stills sums up pretty much some of my questions)

Hi. I don't know if it's the right place to talk about the current online version but here are some precisions I think these should be cleared for a better future :
-  Multiples games have different names abroad the different release zones. Of course, japanese ones are the most frequent (ahem Pocket Monsters became Pokémon out of Japan) but some changes are too done between the PAL and NTSC zones (Contra became Probobector in PAL IIRC). Changes should be made to support naming for different regions or making aliases and redirect to a specific version (for instance US NTSC) or it would make something like a half-doublon.
- Same for release dates. Different regions and different release dates.
- One user, knowing the month but not finding the exact date could set only the month/year and not the day.
- What about early access/constant developpment games or physical only games? Should we put the first beta release date or wait until the 1.0 is out to write it?
- Something that's frontend independant but still related : what's the current rules to upload a picture as cover? I'm still wondering how I could support them with the Haxe frontend.

**Comment by Wifsimster** [comment]
Hi,

Thanks for all these questions. I'll try to respond the best i can.
- I agree with what you just said. But currently the title should be valued in english (most open API provide EN titles).

I will try to think of a solution in the game model to take this in point, maybe something like that :

```
{title: [{country: "countryCode", name: "gameTitle"}]}
```
- Same from release date :

```
{releaseDate: [{country: "countryCode", date: "releaseDate"}]}
```
- Day will be needed in all cases, if the day is unknown the first of the month is alright. Anyway, this is not a critical data.
- Pertinent question... I can add a version attribute like this :

```
{versions: [{number: "gameVersion", date: "releaseDate"}]}
```
- The actual structure for media is :

```
media: {
        boxArt: {
            front: String,
            rear: String
        },
        thumbnails: [String],
        logos: [String],
        banners: [String],
        fanArt: [String],
        screenshots: [String],
        trailers: [String]
    },
```

I'm not favorable to upload media directly on my server. I don"t think that's a sustainable solution. Currently, I'm using media URL from Metacritic API. Best use here, is to get URL from serious web sites (Metacritic, SensCritique, ...).
